language: node_js
node_js:
  - node

dist: trusty
sudo: required

branches:
only:
  - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build dsmaterial-web --prod --base-href https://diegoavieira.github.io/dsmaterial-workspace/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/dsmaterial-web
  on:
    branch: master
