dist: trusty
os: linux

language: node_js
node_js: node

jobs:
  include:
    - stage: release
      name: 'lerna version'
      script:
        - npm run publish:version

    - stage: release
      name: 'dsmaterial-pages'
      script:
        - npm run build:dsmaterial-pages
      before_deploy:
        - cd dist/dsmaterial-pages
      deploy:
        provider: npm
        skip_cleanup: true
        edge: true
        email: 'diegoavieira@gmail.com'
        api_token: $NPM_TOKEN
        on:
          branch: master

    - stage: release
      name: 'dsmaterial-commons'
      script:
        - npm run build:dsmaterial-commons
      before_deploy:
        - cd dist/dsmaterial-commons
      deploy:
        provider: npm
        skip_cleanup: true
        edge: true
        email: 'diegoavieira@gmail.com'
        api_token: $NPM_TOKEN
        on:
          branch: master
