dist: trusty
os: linux

language: node_js
node_js: node

branches:
  only: master

jobs:
  include:
    - stage: release dsmaterial-pages
      script:
        - npm run lint:dsmaterial-pages
        - npm run build:dsmaterial-pages
      before_deploy:
        - cd dist/dsmaterial-pages
      deploy:
        provider: npm
        cleanup: true
        edge: true
        email: 'diegoavieira@gmail.com'
        api_token: $NPM_TOKEN
        on:
          branch: master
