language: node_js
node_js:
  - '10'

dist: trusty
sudo: required

jobs:
  include:
    - stage: npm release
      name: 'dsmaterial-pages'

      script:
        - npm run build:dsmaterial-pages

      before_deploy:
        - cd dist/dsmaterial-pages

      deploy:
        provider: npm
        email: diegoavieira@gmail.com
        api_key: $NPM_TOKEN
        on:
          branch: master
