dist: trusty
os: linux

language: node_js
node_js: node

branches:
  only:
    - master

jobs:
  include:
    - stage: release
      name: 'dsmaterial-pages'
      script:
        - npm run semantic-release
        - npm run build:dsmaterial-pages
      before_deploy:
        - cd dist/dsmaterial-pages
      deploy:
        provider: npm
        skip_cleanup: true
        edge: true
        email: 'diegoavieira@gmail.com'
        api_token: $NPM_TOKEN

    - stage: release
      name: 'dsmaterial-commons'
      script:
        - npm run semantic-release
        - npm run build:dsmaterial-commons
      before_deploy:
        - cd dist/dsmaterial-commons
      deploy:
        provider: npm
        skip_cleanup: true
        edge: true
        email: 'diegoavieira@gmail.com'
        api_token: $NPM_TOKEN
